version: '3'

services:
  qbpnest:
    build:
      context: .
      dockerfile: Dockerfile
    image: qbpnest
    container_name: qbpnest
    restart: unless-stopped
    volumes:
      - qbp_uploads:/app/uploads
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    depends_on:
      - qbp_db

  qbp_db:
    image: postgres:11
    container_name: qbp_db
    restart: unless-stopped
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max_old_space_size=4096
    ports:
      - 5432:5432
    volumes:
      - qbp_db:/var/lib/postgresql/data
    command: 'postgres -N 500'

  redis:
    container_name: redis
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - /data

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - qbpnest

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email qbplatform1@gmail.com --agree-tos --no-eff-email --force-renewal -d api.qbplatform.com  -d www.api.qbplatform.com

volumes:
  certbot-etc:
  certbot-var:
  db_data:
  db_data_test:
  qbp_db:
  qbp_uploads:
  web-root:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/dhparam/
      o: bind


