export enum Role {
	CLIENTADMIN = 'CLIENTADMIN',
	CLIENTMANAGER = 'CLIENTMANAGER',
	CLIENTEMPLOYEE = 'CLIENTEMPLOYEE',
	CLIENTACCOUNTANT = 'CLIENTACCOUNTANT',
	OWNERADMIN = 'OWNERADMIN',
	OWNERMANAGER = 'OWNERMANAGER',
	OWNERSUPPORT = 'OWNERSUPPORT',
	SUBCLIENT = 'SUBCLIENT',
}
