#-------------------
# Deploy api qbpbackend app to api.qbpaltform.com server
#-------------------
name: Deploy_Backend_To_Production_Server
on:
  workflow_dispatch:

#  push:
#    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clone qbp-main repository
      uses: actions/checkout@v1 
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: unnecessary

    - name: Adding Known Hosts
      run: ssh-keyscan -p ${{ secrets.SSH_BACKEND_PORT }} -H ${{ secrets.SSH_BACKEND_HOST }}  >> ~/.ssh/known_hosts  
      
    - name: Start docker-compose up -d --build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_BACKEND_HOST }}
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd ${{ secrets.SSH_BACKEND_PATH }}
          git pull origin main
          docker stop qbpnest
          docker rm qbpnest
          docker rmi qbpnest
          docker-compose up -d --build
          echo "Application successfully deployed." 

        
      
      
